version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
      image: chat_gpt_telegram:latest
    container_name: febrari_GPTbot
    volumes:
      - .:/app
    restart: unless-stopped

